name: Keep Service Warm

on:
  schedule:
    #Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the health check endpoint
        run: curl -X GET https://fastapi-hosting.onrender.com/search?query=liver